Feature/add action yml
moneymeets/action-setup-poetry pull request #1
Opened 2021-02-11 07:28 UTC by marns93

2021-02-11 07:43 UTC, stohrendorf requested changes

2021-02-11 07:43 UTC, stohrendorf commented on action.yml
> +        curl -O -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
Das liegt mittlerweile unter https://github.com/python-poetry/poetry.

Außerdem lässt sich das wie da in der Readme beschrieben vereinfachen zu `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --yes --version=${{ inputs.version }}`

2021-02-11 07:43 UTC, stohrendorf commented on README.md
> +      uses: moneymeets/action-setup-poetry@v1
Ich weiß nicht genau was ich hier denken will... wenn wir hier die Default-Version ändern, müssen wir grundsätzlich immer ein neues `@v` vergeben, damit das bei Leuten, die da nichts explizit setzen, nicht dazu führt, dass die unbemerkt eine neue Version untergeschoben bekommen, und dann haben wir ganz schnell viele Versionen, die von den Bezeichnungen nicht zu den Poetry-Versionen passen. Daher zwei Alternativ-Vorschläge:
* die `@v`-Versionen sind die gleichen wie Poetry, und wir nehmen die Konfigurierbarkeit raus, oder
* es gibt keinen Default für die Poetry-Version und muss immer gesetzt werden.

Ich bin da für letzteres.

2021-02-11 07:57 UTC, marns93 commented on README.md
> +      uses: moneymeets/action-setup-poetry@v1
Ohne den default würde bedeuten, dass wir die Version dann perspektivisch in x Repositories jedes mal anpassen müssen. Ich glaube nicht, dass es das ist was wir wollen.

Mit dem Tag stimme ich dir zu und das muss anders gelöst werden.

Wenn wir unsere Repositories nicht jedesmal alle anpassen möchten, sondern nur den `default` in der Action, würde das bedeuten, dass wir für uns keine Tags verwenden, sondern immer master nehmen.

Was denken die anderen an dieser Stelle?
Mein Ziel wäre es bei Updates von Poetry nur eine einzige Stelle anpassen zu müssen, und da kommt für mich eigentlich nur die Action in Frage.

2021-02-11 08:07 UTC, marns93 commented on action.yml
> +        curl -O -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
Danke für den Hinweis, werde ich anpassen.

Ich hatte es in einzelnen Kommandos gemacht, weil ich es etwas übersichtlicher fand, kann aber mit beiden Vorschlägen leben.

2021-02-11 08:10 UTC, stohrendorf commented on README.md
> +      uses: moneymeets/action-setup-poetry@v1
Wenn der Tag mit der Poetry-Version gleichgezogen wird, ist das aber dasselbe Problem, nur dass dann in den Repos auf ein anderes Tag gewechselt werden muss anstatt eine Variable anzupassen. Auf der anderen Seite kannst du reproducible builds vergessen wenn nur ein generelles `@v1` genommen wird. Ich glaube die Frage ist halt ob wir reproducible builds haben wollen oder nicht.

2021-02-11 08:16 UTC, marns93 commented on README.md
> +      uses: moneymeets/action-setup-poetry@v1
Die Frage ist, was wir am Ende haben möchten.

Ich kann damit leben einfach für unseren Fall `@master` zu nehmen. Somit können wir den `default` in der Action hochziehen und brauchen weiter nichts zu machen, haben aber Kontrolle über die Poetry Versions upgrades.

Wenn eine neue Poetry Version kommt, kann man einen Feature Branch machen, den `default` hochziehen und in einem unserer Repos dann den speziellen Commit testen. Wenn alles klappt, kann man in `master` mergen und alle anderen Pipelines arbeiten mit der neuen Version. Mit den Tags finde ich etwas hinderlich an der Stelle.

2021-02-11 17:31 UTC, zyv commented on README.md
> +      uses: moneymeets/action-setup-poetry@v1
Genau so.

2021-02-11 17:32 UTC, zyv approved these changes

2021-02-11 19:49 UTC, mm-matthias approved these changes
Zu der Versionierungsdiskussion: Ich glaube hier kann man einfach ausprobieren. Wenn langfristig irgendwelche Probleme durch das zentrale Upgrade der Poetry-Master-Version entstehen, kann man immer noch jederzeit dazu übergehen, in den einzelnen Repositories spezifische Versionen zu pinnen. Das spart uns zunächst eine Menge Aufwand.

2021-02-12 08:19 UTC, stohrendorf approved these changes

2021-02-12 08:24 UTC, merged